# Generated by Django 6.0.3 on 2026-04-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(db_column='room_number', max_length=10, unique=True)),
                ('room_type', models.CharField(db_column='room_type', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_night', models.DecimalField(db_column='price_per_night', decimal_places=2, max_digits=10)),
                ('max_occupancy', models.IntegerField(db_column='max_occupancy')),
                ('available', models.BooleanField(default=True)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, db_column='image_url', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
                ('status', models.CharField(blank=True, default='DIRTY', max_length=20, null=True)),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
    ]
