# Generated by Django 6.0.3 on 2026-03-15 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(db_column='booking_reference', max_length=100, unique=True)),
                ('check_in_date', models.DateField(db_column='check_in_date')),
                ('check_out_date', models.DateField(db_column='check_out_date')),
                ('number_of_guests', models.IntegerField(db_column='number_of_guests')),
                ('number_of_nights', models.IntegerField(db_column='number_of_nights')),
                ('total_amount', models.DecimalField(db_column='total_amount', decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(db_column='deposit_amount', decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(db_column='remaining_amount', decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING_DEPOSIT', 'Pending Deposit'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING_DEPOSIT', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('DEPOSIT_PAID', 'Deposit Paid'), ('FULLY_PAID', 'Fully Paid')], db_column='payment_status', default='UNPAID', max_length=20)),
                ('special_requests', models.TextField(blank=True, db_column='special_requests', null=True)),
                ('deposit_payment_id', models.CharField(blank=True, db_column='deposit_payment_id', max_length=200, null=True)),
                ('balance_payment_id', models.CharField(blank=True, db_column='balance_payment_id', max_length=200, null=True)),
                ('deposit_paid_at', models.DateTimeField(blank=True, db_column='deposit_paid_at', null=True)),
                ('balance_paid_at', models.DateTimeField(blank=True, db_column='balance_paid_at', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('requested_checkin', models.DateField(blank=True, null=True)),
                ('requested_checkout', models.DateField(blank=True, null=True)),
                ('requested_room_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
