# Generated by Django 6.0.3 on 2026-04-09 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('middle_name', models.CharField(blank=True, db_column='middle_name', max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(db_column='date_of_birth')),
                ('contact_number', models.CharField(db_column='contact_number', max_length=30)),
                ('emergency_contact', models.CharField(blank=True, db_column='emergency_contact', max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, db_column='emergency_phone', max_length=30, null=True)),
                ('home_address', models.TextField(db_column='home_address')),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('employee_id', models.CharField(db_column='employee_id', max_length=50, unique=True)),
                ('department', models.CharField(choices=[('FRONT_DESK', 'Front Desk'), ('HOUSEKEEPING', 'Housekeeping'), ('MAINTENANCE', 'Maintenance'), ('SECURITY', 'Security'), ('FOOD_BEVERAGE', 'Food & Beverage'), ('MANAGEMENT', 'Management'), ('ADMIN', 'Administration')], db_column='department', max_length=20)),
                ('position', models.CharField(choices=[('RECEPTIONIST', 'Receptionist'), ('HOUSEKEEPER', 'Housekeeper'), ('STAFF', 'Staff'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator')], db_column='position', max_length=20)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('PROBATIONARY', 'Probationary'), ('CASUAL', 'Casual')], db_column='employment_type', default='FULL_TIME', max_length=20)),
                ('salary', models.DecimalField(blank=True, db_column='salary', decimal_places=2, max_digits=10, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, db_column='hourly_rate', decimal_places=2, max_digits=8, null=True)),
                ('hire_date', models.DateField(db_column='hire_date')),
                ('regularized_date', models.DateField(blank=True, db_column='regularized_date', null=True)),
                ('termination_date', models.DateField(blank=True, db_column='termination_date', null=True)),
                ('skills', models.TextField(blank=True, db_column='skills', null=True)),
                ('certifications', models.TextField(blank=True, db_column='certifications', null=True)),
                ('education', models.TextField(blank=True, db_column='education', null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_on_duty', models.BooleanField(db_column='is_on_duty', default=True)),
                ('sss_number', models.CharField(blank=True, db_column='sss_number', max_length=50, null=True)),
                ('philhealth_number', models.CharField(blank=True, db_column='philhealth_number', max_length=50, null=True)),
                ('pagibig_number', models.CharField(blank=True, db_column='pagibig_number', max_length=50, null=True)),
                ('tin_number', models.CharField(blank=True, db_column='tin_number', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_information', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_information',
            },
        ),
    ]
