# Generated by Django 6.0.3 on 2026-04-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencyalert_guest_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
    ]
