# Generated by Django 6.0.3 on 2026-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='Cebu Grand Hotel', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='12:00')),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('points_per_php', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Settings',
                'db_table': 'hotel_settings',
            },
        ),
    ]
