# Generated by Django 6.0.3 on 2026-04-11 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('ROOM_CLEANING', 'Room Cleaning'), ('BATHROOM_CLEANING', 'Bathroom Cleaning'), ('LINEN_CHANGE', 'Linen Change'), ('DEEP_CLEANING', 'Deep Cleaning'), ('PUBLIC_AREA', 'Public Area Cleaning')], max_length=30)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('room_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('before_image', models.CharField(blank=True, max_length=500, null=True)),
                ('after_image', models.CharField(blank=True, max_length=500, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.booking')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
            ],
            options={
                'db_table': 'cleaning_tasks',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CleaningChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='housekeepers.cleaningtask')),
            ],
            options={
                'db_table': 'cleaning_checklists',
            },
        ),
        migrations.CreateModel(
            name='Housekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('hire_date', models.DateField()),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (6AM - 2PM)'), ('AFTERNOON', 'Afternoon (2PM - 10PM)'), ('NIGHT', 'Night (10PM - 6AM)')], default='MORNING', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_DUTY', 'On Duty'), ('ON_BREAK', 'On Break'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('skills', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeper_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'housekeepers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cleaningtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='housekeepers.housekeeper'),
        ),
        migrations.CreateModel(
            name='RoomStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('CLEANED', 'Cleaned'), ('INSPECTED', 'Inspected'), ('DIRTY', 'Marked Dirty'), ('MAINTENANCE', 'Maintenance Required')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housekeepers.housekeeper')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='rooms.room')),
            ],
            options={
                'db_table': 'room_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('housekeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_requests', to='housekeepers.housekeeper')),
            ],
            options={
                'db_table': 'supply_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
